### ISSUE TITLE
User id instead of "user" name

### ISSUE THREAD

**Issue by amviro** [bestmomo/filemanager#1]
Hello,
Is there any way to use user's numeric id instead of user name?

Regards

**Comment by bestmomo** [comment]
Hello,
Thanks.
Maybe it's a better idea to use id instead of user name. I think I'll make an update.

Regards

**Comment by bestmomo** [comment]
Changed in [this commit](https://github.com/bestmomo/filemanager/commit/4344bb41a6c955907b803602f02221609442c9cc) with V 1.01

**Comment by amviro** [comment]
Great!! Thanks
