### ISSUE TITLE
Cannot rename folder/files

### ISSUE THREAD

**Issue by AEK-BKF** [bestmomo/filemanager#15]
Hi,
Thanks for package,
I installed it successfully and it works fine except renaming folders / files !
When I try to rename something I get this error : No Way , 
Please could you help me ? thanks

**Comment by bestmomo** [comment]
Hi,
What do you want to rename ?

**Comment by AEK-BKF** [comment]
It's ok now :)) (see : [https://github.com/simogeo/Filemanager/issues/471#issuecomment-194904271](url) )

I've an other question, I used your accessMediasAll and accessMediasFolder functions in User model, it works fine but could you redirect users who don't have access to "/filemanager" route to "home" for example ?

**Comment by bestmomo** [comment]
You should not logically find yourself in this situation to go on filemanager page with a no authorized user. Though it's filemanager code so I dont think you can do a redirection.

**Comment by AEK-BKF** [comment]
Ok thanks :)
