### ISSUE TITLE
remove this line $fm->setFileRoot($folderPath);

### ISSUE THREAD

**Issue by AmrAlfoly** [bestmomo/filemanager#17]
i had a week of delay because of it

**Comment by bestmomo** [comment]
Hi,
This line is to set the path that is in config file, why do you need to remove it ?

**Comment by AmrAlfoly** [comment]
because when i pushed the site to production i had the script giving errors like no way and the path is not right and it turns out that i have to specify the folder path in the fileroot option and this line must be removed so the script work well
