### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by noxify** [bestmomo/filemanager#2]
Hi,

you have to change `Bestmomo\Filemanager\ScafoldServiceProvider::class` to `Bestmomo\Filemanager\FilemanagerServiceProvider::class` in your README :)

greets

**Comment by bestmomo** [comment]
Hi,

Good catch ;)

Corrected in [this commit](https://github.com/bestmomo/filemanager/commit/9e918d210cea271884827953e9c7d79c26f5c129).
