### ISSUE TITLE
How to add custom upload directory?

### ISSUE THREAD

**Issue by amviro** [bestmomo/filemanager#3]
Hello,
Where do I set upload directory?
I've moved filemanager to **public/assets/filemanager/** and want to upload files in **public/images/**

`
filebrowserBrowseUrl: '<?php echo url("assets/filemanager/index.html"); ?>',
`

Pls give me some hint how I can dot it.
Regards

**Comment by bestmomo** [comment]
Hello,

In filemanager/connectors/default.config.php change these lines :

```
require getcwd() . '/../../../../../bootstrap/autoload.php';
$app = require_once getcwd() . '/../../../../../bootstrap/app.php';
```

So filemanager will work. 

But I dont know how to change upload folder. You should ask it to [simogeo](https://github.com/simogeo/Filemanager).

**Comment by amviro** [comment]
I found just few lines after the code you mentioned

```
// Folder path
$folderPath = $app->basePath() . '/public/images/'; 
```

**Comment by bestmomo** [comment]
Right ;)
