### ISSUE TITLE
'/filemanager/filemanager/userfiles/user...'  on the input box labeled 'URL' in 'Image Info' tab 

### ISSUE THREAD

**Issue by justinFather** [bestmomo/filemanager#4]
Hi,

 '/filemanager/filemanager/userfiles/user...' appears  on the input box labeled 'URL' in 'Image Info' tab, when I select the image file. It is supposed to be '/filemanager/userfiles/user...'.

My 'User.php' file has two methods as below

---

```
public function accessMediasAll()
{
    return false; 
}    
public function accessMediasFolder()
{
    return true; 
}    
```

---

Regards

**Comment by bestmomo** [comment]
Hi,

In public/filemanager/scripts/filemanager.config.js change this line :

```
"baseUrl": "/filemanager/",
```

For this one :

```
"baseUrl": "/",
```

**Comment by justinFather** [comment]
Now it works fine. Thank you very much.

PS.
I made ko.js (korean language) . If you want it, I will help you with it.
