### ISSUE TITLE
authorization problem

### ISSUE THREAD

**Issue by shakilmahbub** [bestmomo/filemanager#6]
I am using laravel 5.1. I am trying to install this file manager. every thing is ok but when I am trying to upload file the file manager show the a message "You are not authorized to use filemanager." I use the function public function accessMediasAll(){
    return true; 
}  
public function accessMediasFolder(){
    return true; 
}  in user model. But still I have the problem. and One thing I do not using any model file to make query . i am using the controller file to do all of the query. What can I do now? One more thing this time I am using this with ck editor . how can I use this file manager with tynemce editor??

**Comment by bestmomo** [comment]
Hi,

You can debug this in `public/filemanager/connectors/php/default.config.php`.

For tinyMCE intergration look at [this page](https://github.com/simogeo/Filemanager/wiki/How-to-use-the-Filemanager-with-tinyMCE--3-or-4-%3F).

**Comment by shakilmahbub** [comment]
thank you

**Comment by shakilmahbub** [comment]
I got another problem. when I upload a picture It do not show show in the editor I mine the link of the picture is wrong. I see on the source the link is something like "/filemanager/userfiles/Nature-Tourism.png" but it should be like "filemanager/userfiles/Nature-Tourism.png" this. the "/" should be remove from front of the link. how can I remove this??

**Comment by shakilmahbub** [comment]
I fix that.
